version: "3.5"
services:
  # api
  nongki-test:
    container_name: nongki-test
    image: nongki-test:latest
    ports:
      - "3030:3030"
    depends_on: 
      - nongki-test-postgres
      - nongki-test-redis
    networks:
      - nongki-test-net
    
  # postgres
  nongki-test-postgres:
    container_name: nongki-test-postgres
    image: postgres:12-alpine 
    environment: 
      - POSTGRES_USER=nongki-test_user
      - POSTGRES_PASSWORD=supernongki-test
      - POSTGRES_DB=golang_rest_boilerplate_db
    volumes: 
      - nongki-test-postgres:/var/lib/postgresql
    ports:
      - "5432:5432"
    networks:
      - nongki-test-net
  
  # redis
  nongki-test-redis:
    image: "redis:alpine"
    container_name: nongki-test-redis
    command: redis-server --requirepass 21541e54-d91c-4c4b-ab94-26fa5a46a654
    environment:
      - REDIS_REPLICATION_MODE=master
    volumes:
      - nongki-test-redis:/var/lib/redis
      - nongki-test-redis-conf:/usr/local/etc/redis/redis.conf
    ports:
      - "6379:6379"
    restart: always
    networks:
      - nongki-test-net
  
volumes:
  nongki-test-postgres:
    external: false
  nongki-test-redis:
    external: false
  nongki-test-redis-conf:
    external: false
  
networks:
  nongki-test-net:
    name: nongki-test-net
